# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <filter_youtube_data>
  "channel_type",
  # <filter_youtube_data>
  "country",
  # <filter_youtube_data>
  "formatted_subscribers",
  NULL
))
